project:
  type: book
  output-dir: _book
  preview:
    port: 5555
    browser: false

book:
  title: "ciência de dados _notas"
  author:
    - name: Roney Fraga Souza
      affiliations:
        - name: Universidade Federal de Mato Grosso
  date: "today"
  date-format: iso 
  search: true
  reader-mode: true
  repo-actions: [edit, issue]
  sharing: [twitter, facebook]
  twitter-card: true
  site-url: https:roneyfraga.com/cidados
  repo-url: https://github.com/roneyfraga/cidados

  page-footer:
    left: |
      Notas sobre Ciência de Dados, Análise de Dados e Programação.
    right: |
      Material construído com <a href="https://quarto.org/">Quarto</a>.

  chapters:
    - index.qmd

    # - part: excel básico 
    #   chapters:

    - part: r.qmd 
      chapters:
        - r-01.qmd
        - r-02.qmd
        - r-03.qmd
        - r-04.qmd
        - r-05.qmd
        - r-06.qmd
        - r-07.qmd

    - part: julia.qmd
      chapters:
        - jl-introducao.qmd

    - part: python.qmd
      chapters:
        - py-introducao.qmd
        - py-pandas-numpy.qmd
        # - py-networks.qmd

    # - part: redes.qmd
        # tidygraph
        # ggraph
        # bipartite (diretório já existe)
        
    # - part: analise-de-texto.qmd
        # tidytext
        # processamento de linguagem natural
        # structutal topic modeling 

    # - part: aprendizado de máquina

    - part: projetos.qmd
      chapters:
        - prj-um-bilhao.qmd
        - prj-flexdashboard.qmd
        - prj-ojs-downloader.qmd
        - prj-wos-downloader.qmd
        - prj-caged-download.qmd
        - prj-res-ping.qmd
        - prj-dicionario-sinonimos.qmd
        - prj-tabela-binaria.qmd
        - prj-leitura-ris.qmd
        - prj-write-ris-lattes.qmd
        - prj-diagrama.qmd
        - prj-dea.qmd

    - references.qmd

lang: pt
bibliography: references.bib
csl: abnt-ipea.csl

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    toc-location: right
    code-fold: show
    code-line-numbers: true
    author-meta: "Roney Fraga Souza"

execute:
  cache: true
